config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }

 get 'comprar/:id', to: 'products#comprar', as: 'comprar'

 get 'usuario/:id', to: 'products#profile', as: 'profile'
 get 'misventas', to: 'products#ventas', as: 'ventas'

 root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(enable: true)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end


# Boton comprar
  def comprar
    @product = Product.find(params[:id])
    @product.enable = false
    @product.save
    redirect_to root_path, notice: 'Producto comprado'
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  #Método perfil
  def profile
    @user = User.find(params[:id])
  end

#Método ventas
  def ventas
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'El producto fue creado' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'El producto fue actualizado' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'El producto fue eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :photo, :price, :enable)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yapo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

  </head>

  <body class="body-custom">
  <%= render 'shared/navbar' %>

  <div class="alert-wrap">
      <% if notice %>
        <div class="alert alert-custom alert-cont">
          <button type="button" class="close close-custom" data-dismiss="alert">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= alert %></p>
        </div>
      <% end %>
    </div>


      <%= yield %>

    <footer>
      <p><strong>Yapo</strong> APP Desafío Latam</p>
      <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tempor cursus urna, at auctor
        velit accumsan eget. Pellentesque a dapibus nibh.</span>
    </footer>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<div class="wrap-form">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group form-group-custom">
      <%= form.label :name, "Nombre" %>
      <div>
        <%= form.text_field :name, id: :product_name %>
      </div>
    </div>

    <div class="form-group form-group-custom">
      <%= form.label :description, "Descripción" %>
      <div>
        <%= form.text_field :description, id: :product_description %>
      </div>
    </div>

    <div class="form-group form-group-custom">
      <%= form.label :photo, "URL imagen" %>
      <div>
        <%= form.text_field :photo, id: :product_photo %>
      </div>
    </div>

    <div class="form-group form-group-custom">
      <%= form.label :price, "Precio" %>
      <div>
        <%= form.text_field :price, id: :product_price %>
      </div>
    </div>

    <div class="form-group form-group-custom">
      <%= form.label :enable, "Disponible" %>
      <div>
        <%= form.check_box :enable, id: :product_enable %>
      </div>
    </div>

    <div class="form-group">
    <div>
      <%= form.submit "Subir"%>
      <%= link_to 'Volver', products_path, class: 'volver' %>
    </div>
  </div>

  </fieldset>

<% end %>
</div>

app/views/products/edit.html.erb
<div class="wrap-container wrap-container-new">

  <div class="new-top">

    <h1>Editar producto</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      Quae asperiores error omnis saepe tempore.</p>

      <div class="bg-trame"></div>

  </div>



  <%= render 'form', product: @product %>


</div>

app/views/products/index.html.erb
<div class="wrap-container">

<% @products.reverse.each do |product| %>

      <div class="product-card">

        <div style="background-image:url(<%= product.photo %>)" class="image-product"></div>
        <div class="info">

          <span><%= product.price %></span>
          <h1><%= product.name %></h1>
          <p><%= product.description %></p>

          <div class="circle">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>

          <% if user_signed_in? %>

          <nav class="link-product">
            <ul>
              <li>
                <%= link_to 'Ver Producto', product %>
              </li>
              <% if user_signed_in? && (current_user.id == product.user_id) %>

              <% else %>
              <li>
                <%= link_to 'Comprar', comprar_path(product) %>
              </li>
              <% end %>

            </ul>
          </nav>

          <% if user_signed_in? && (current_user.id == product.user_id) %>

            <%= link_to '', edit_product_path(product), class: "btn-editar" %>
            <%= link_to '', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-eliminar" %>

            <div class="access">
              <%= link_to '', edit_product_path(product), class: "btn-editar" %>
              <%= link_to '', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-eliminar" %>
            </div>

          <% end %>

          <% else %>


          <nav class="link-product">
            <ul>
              <li>
                <%= link_to 'Ver Producto', product %>
              </li>
              <li>
                <a href="<%= new_user_session_path %>">Comprar</a>
              </li>
            </ul>
          </nav>

        <% end %>

        </div>

      </div>

<% end %>


</div>

app/views/products/new.html.erb
<div class="wrap-container wrap-container-new">

  <div class="new-top">

    <h1>Nuevo producto</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      Quae asperiores error omnis saepe tempore.</p>

      <div class="bg-trame"></div>

  </div>



  <%= render 'form', product: @product %>


</div>

app/views/products/profile.html.erb
<div class="wrap-container wrap-container-profile">

  <div class="profile-wrap">

    <div class="profile-card">
      <figure></figure>
      <h1><%= @user.name %></h1>
      <a href=""><%= @user.email %></a>
      
    </div>

  </div>


</div>

app/views/products/show.html.erb
<div class="wrap-container">

  <article class="wrap-show">

    <div>
      <figure style="background-image:url(<%= @product.photo %>)">
      </figure>
    </div>

    <div>
      <p class="star"><span>Customer Reviews:</span>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
      </p>
      <h1><%= @product.name %></h1>
      <h3>Publicado por: <%= link_to @product.user.name, profile_path(@product.user), class: 'user' %></h3>
      <p><%= @product.description %></p>
      <h2><%= @product.price %></h2>

      <% if user_signed_in? && (current_user.id == @product.user_id) %>
        <%= link_to 'Editar', edit_product_path(@product), class: 'editar' %>
      <% elsif user_signed_in? %>
        <%= link_to 'Comprar', comprar_path(@product) %>
      <% else %>
        <a href="<%= new_user_session_path %>">Comprar</a>
      <% end %>



    </div>

  </article>

<div class="access-bot">
    <%= link_to 'Volver al Home', products_path, class: 'volver' %>
</div>
</div>

app/views/products/ventas.html.erb
<div class="wrap-container wrap-container-ventas">
<h1>Mis ventas</h1>

<article class="ventas-wrap">
  <div>
    <h1><i class="fas fa-bullseye"></i> Productos Vendidos</h1>

    <% @products.each do |product| %>
    <div class="cont-product">

    <% if product.enable == false %>
    <figure style="background-image:url(<%= product.photo %>)">
    </figure>
    <div>
      <h2><%= product.name %></h2>
      <p><%= product.description %></p>
      <nav>
        <ul>
          <li>
            <%= link_to '', edit_product_path(product), class: "btn-editar" %>
          </li>
          <li>
            <%= link_to '', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-eliminar" %>
          </li>
        </ul>
      </nav>
      </div>
      <% end %>

    </div>
    <% end %>

  </div>

  <div>
    <h1><i class="fas fa-laptop"></i> Productos Publicados</h1>

    <% @products.each do |product| %>
    <div class="cont-product">

    <% if product.enable == true %>
    <figure style="background-image:url(<%= product.photo %>)">
    </figure>
    <div>
      <h2><%= product.name %></h2>
      <p><%= product.description %></p>
      <nav>
        <ul>
          <li>
            <%= link_to '', edit_product_path(product), class: "btn-editar" %>
          </li>
          <li>
            <%= link_to '', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-eliminar" %>
          </li>
        </ul>
      </nav>
      </div>
      <% end %>


    </div>
    <% end %>

  </div>
</article>

</div>

app/views/shared/_navbar.html.erb
<div class="container-menu">
  <div class="container container-nav-custom">

    <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
        <a class="navbar-brand brand-custom" href="<%= root_path %>">yapo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
            </ul>


            <ul class="navbar-nav navbar-nav-custom">

              <% if user_signed_in? %>

              <li class="nav-item"><%= link_to 'Publicar producto', new_product_path, class:'publicar' %></li>
              <li class="nav-item"><%= link_to 'Mis ventas', ventas_path %></li>

              <li class="nav-item">
                <a href="<%= profile_path(current_user) %>" class="name">
                  <%= current_user.name %>
                </a>

              </li>

              <li class="nav-item"><a href="<%= destroy_user_session_path %>" class="salir" data-method="DELETE"><i class="fas fa-power-off"></i></a></li>

              <% else %>
              <li class="nav-item"><a href="<%= new_user_session_path %>">Ingreso</a></li>
              <li class="nav-item"><a href="<%= new_user_registration_path %>" class="reg">Registro</a></li>
              <% end %>
            </ul>
        </div>
    </nav>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <p>¿Ya tienes una cuenta? <%= link_to "Inicia sesión", new_session_path(resource_name) %><br /></p>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <p>¿Tienes una cuenta? <%= link_to "Regístrate", new_registration_path(resource_name) %><br /></p>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <p><%= link_to "¿Olvidaste tu contraseña?", new_password_path(resource_name) %><br /></p>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>